require("dotenv").config();
const express = require("express");
const userRouter = require("./router/user");
const authRouter = require("./router/auth");
const tripRouter = require("./router/trip");
// const categoryRouter = require("./router/category");
// const ordersRouter = require("./router/order");
const authMiddleware = require("./auth/middleware");
const cors = require("cors");
const app = express();
const port = 5000;
const jsonParser = express.json();

app.use(cors());
app.use(jsonParser);
app.use("/auth", authRouter);
app.use("/users", userRouter);
app.use("/trips", tripRouter);
// app.use("/category", categoryRouter);
// app.use("/orders", ordersRouter);
app.listen(port, () => console.log("Listening to port", port));
